// Copyright (c) Petabridge <https://petabridge.com/>. All rights reserved.
// Licensed under the Apache 2.0 license. See LICENSE file in the project root for full license information.
// See ThirdPartyNotices.txt for references to third party code used inside Helios.

// <auto-generated/>

using System.Reflection;

[assembly: AssemblyCompanyAttribute("Helios Framework")]
[assembly: AssemblyCopyrightAttribute("Copyright © Aaron Stannard 2013-2015")]
[assembly: AssemblyVersionAttribute("2.1.1")]
[assembly: AssemblyFileVersionAttribute("2.1.1")]