// <auto-generated/>
using System.Reflection;

[assembly: AssemblyCompanyAttribute("Helios Framework")]
[assembly: AssemblyCopyrightAttribute("Copyright © Aaron Stannard 2013-2015")]
[assembly: AssemblyVersionAttribute("2.0.2")]
[assembly: AssemblyFileVersionAttribute("2.0.2")]
