// <auto-generated/>
using System.Reflection;

[assembly: AssemblyCompanyAttribute("Helios Framework")]
[assembly: AssemblyCopyrightAttribute("Copyright © Aaron Stannard 2013-2015")]
[assembly: AssemblyVersionAttribute("1.4.1.0")]
[assembly: AssemblyFileVersionAttribute("1.4.1.0")]
